---

- src: ome.postgresql

- src: ome.omero_server

- src: ome.omero_web

- src: ome.nginx

- src: ome.ssl_certificate

- src: ome.omero_user

- src: ome.python3_virtualenv

- src: ome.ice

- src: ome.selinux_utils
